config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "items#index"
  resources :items do
    collection do
      get 'exhibit'
      get 'confirm'
      get 'error'
      post 'pay'
      get 'category'
    end
    resources :images, only: [:index, :create]
    resources :goods, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  namespace :api do
      resources :categories, only: :index, defaults: { format: 'json' }
    end
  namespace :api do
    resources :sizetypes, only: :index, defaults: { format: 'json' }
  end
  namespace :api do
    resources :brands, only: :index, defaults: { format: 'json' }
  end

  resources :users, only: [:new, :edit, :show] do
    collection do
      get 'log_out'
      get 'register'  
      get 'sign_in'
    end
  end
  resources :signup, only:[:new, :create] do
    collection do
      get 'outsidemember'
      get 'member'
      get 'phonenumber'
      get 'address'
      get 'paymethod' 
      get 'done' 
    end
  end


  resources :cards do
    collection do
      post 'new'
      post 'create'
    end
  end    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,omniauth_providers: [:facebook, :google_oauth2]
  has_many :items
  has_many :comments
  has_many :messages
  has_many :goods
  has_many :items, through: :goods
  has_many :addresses
  has_many :cards
  has_many :sns_credentials, dependent: :destroy

  accepts_nested_attributes_for :addresses

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :year
    belongs_to_active_hash :month
    belongs_to_active_hash :day

  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :birthdate_year,          presence: true
  validates :birthdate_month,         presence: true
  validates :birthdate_day,           presence: true

  validates :cellphone_number,        presence: true

  validates :address_last_name,       presence: true
  validates :address_first_name,      presence: true
  validates :address_last_name_kana,  presence: true
  validates :address_first_name_kana, presence: true

  validates :card_number,             presence: true
  validates :expiration_year,         presence: true
  validates :expiration_month,        presence: true

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.find_by(uid: uid)
    
    if snscredential.present?
      user = User.find(snscredential.user_id)
      unless user.present?
        generated_password = Devise.friendly_token[0, 20]
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
          password: generated_password,
          password_confirmation: generated_password
        )
      end
      sns = snscredential
    else
      user = User.find_by(email: auth.info.email)
      if user.present?
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
          password: generated_password,
          password_confirmation: generated_password
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return { user: user, sns_id: sns.id }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end
    
  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    sns_id = info[:sns_id]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.sns_id"] = sns_id
      render template: outsidemember_signup_index_path
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# class Users::RegistrationsController < Devise::RegistrationsController
#   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
# end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end
  
  def show
  end
  
  def edit
  end

  def log_out
  end

  def register
  end  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_item__exhibit.html.haml
.item__exhibit
  =link_to class: 'item__exhibit__link' do
    .item__exhibit__content
      .item__exhibit__content__text 出品
      %i.fa.fa-camera.item__exhibit__content__icon

app/views/users/_sideber.html.haml
.side__link
  %ul.side__link__top
    = link_to "" do
      %li 
        .side__link__top--box
          マイページ
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          お知らせ
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          やることリスト
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          いいね！一覧
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          出品する
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          出品した商品-出品中
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          出品した商品-取引中
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          出品した商品-完済済み
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          購入した商品-取引中
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          購入した商品-過去の取引
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          ニュース一覧
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          評価一覧
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          ガイド
          = fa_icon 'angle-right'
    = link_to "" do
      %li 
        .side__link__top--box
          お問い合わせ
          = fa_icon 'angle-right'
  .side__link__merpay
    %h3 メルペイ
    %ul.side__link__merpaylist
      = link_to "" do
        %li 
          .side__link__top--box
            売り上げ・振込申請
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            ポイント
            = fa_icon 'angle-right'
  .side__link__edit
    %h3 設定
    %ul.side__link__editlist
      = link_to "" do
        %li 
          .side__link__top--box
            プロフィール
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            発送元・お届け先住所変更
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            支払い方法
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            メール/パスワード
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            本人情報
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            電話番号
            = fa_icon 'angle-right'
      = link_to "" do
        %li 
          .side__link__top--box
            ログアウト
            = fa_icon 'angle-right'

app/views/users/edit.html.haml
.edit
  = render 'items/header'
  - breadcrumb :profile
  = breadcrumbs separator: " &rsaquo; "
  .main
    = render 'sideber'
    .edit__profile
      .edit__profile--profile
        プロフィール
        .edit__profile--user
          .edit__profile--user--box
            .edit__profile--user--box--image
              = image_tag ""
            %input.edit__profile--user--box--nickname{ placeholder: "名前を入力" }
        %textarea.edit__profile--text{ placeholder: "プロフィールを入力してください"}
        %input.edit__profile--submit{type: 'submit', value: '変更する'}
  = render 'item__exhibit'
  = render 'items/footer'

app/views/users/log_out.html.haml
= render 'items/header'
- breadcrumb :log_out
= breadcrumbs separator: " &rsaquo; "

-# サーバー実装次第form_for(deleteメソッド)
.wrapper
  .main
    = render 'sideber'
    .contents
      .top--content      
        = link_to do  
          .log-out__button.button ログアウト
        
  = render 'item__exhibit'
  = render 'items/footer'

app/views/users/new.html.haml
.contents
  .header-user
    .header-user__logo-default
      = link_to image_tag(src= "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3296506464", class: "mercari-logo", height:49, width:185), "#"
  .main-user
    .main-user__box
      .main-user__box__title
        新規会員登録
      .main-user__box__btns
        .main-user__box__btn
        =link_to member_signup_index_path, class: "main__box__btn main__box__btn--email" do
          = fa_icon 'envelope', class: "main__box__btn--icon"
          メールアドレスで登録する
        .main-user__box__btn
        =link_to user_facebook_omniauth_authorize_path, class: "main__box__btn main__box__btn--facebook" do
          = fa_icon 'facebook-square', class: "main__box__btn--icon"
          Facebookで登録する
        .main-user__box__btn
        =link_to user_google_oauth2_omniauth_authorize_path, class: "main__box__btn main__box__btn--google" do
          = fa_icon 'google', class: "main__box__btn--icon"
          Googleで登録する
  .footer-user
    %ul
      %li= link_to 'プライバシーポリシー', '#'
      %li= link_to 'メルカリ利用規約', '#'
      %li= link_to '特定商取引に関する表記', '#'
    .footer-user__link
    = link_to image_tag(src= "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3296506464", class: "mercari-graylogo", height: 80, width: 60), "#"
    %p © 2019 Mercari

app/views/users/register.html.haml
.wrapper
  = render 'items/header'
  - breadcrumb :card
  = breadcrumbs separator: " &rsaquo; "
  .main
    = render 'users/sideber'
    .right__box
      .right__box__header
        %p.pay 支払い方法
      .right__box__footer
        .right__box__footer__inner
          .right__box__footer__innner__top
            %p.card クレジットカード一覧
          .right__box__footer__inner__middle
            .right__box__footer__inner__middle__border
              %i.far.fa-credit-card
              = link_to "クレジットカードを追加する",(),class:"card"
          .right__box__footer__inner__bottom
            = link_to "支払方法について",(),class: "pay"
            %i.fas.fa-chevron-right
  = render 'item__exhibit'
  = render 'items/footer'

app/views/users/show.html.haml
= render 'items/header'
- breadcrumb :mypage
= breadcrumbs separator: " &rsaquo; "
.wrapper
  .main
    = render 'sideber'
    .contents
      .top--content
        .user__image
          =link_to do
            %img{src:'https://image.flaticon.com/icons/png/512/97/97895.png', height:"60",width:"60"}
            .user__image__name チームE
            .user__image__judges
              .user__image__judges__judge 評価
              %span.user__image__judges__num 0
              .user__image__judges__count 出品数
              %span.user__image__judges__num 0
            
        .message
          %ul.mypage__tabs
            %li.tag__changed お知らせ
            %li やることリスト
          .message__content
            %ul.message__content__tab.active
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text お知らせだよお知らせだよお知らせだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text お知らせだよお知らせだよお知らせだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text お知らせだよお知らせだよお知らせだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              
              %li.message__tab__index
                -# サーバーサイドでき次第form_withに変更
                = link_to '一覧を見る', 'http://google.co.jp'
            
            %ul.message__content__tab
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text やることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text やることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              %li
                =link_to do
                  %img{src:'https://static.mercdn.net/images/mercari_profile.png', height:"48",width:"48"}
                  .message__tab__body
                    .message__tab__body__text やることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよやることだよ
                    .message__tab__body__time
                      .message__tab__body__time__icon
                        %i.fa.fa-clock-o
                        %span １時間前
                  .message__tab__icon
                    %i.fa.fa-chevron-right
              %li.message__tab__index
                -# サーバーサイドでき次第form_withに変更
                = link_to '一覧を見る', 'http://google.co.jp'


      .bottom--content
        %h3.bottom--content__header 購入した商品
        %ul.bottom__mypage__tabs
          %li.tag__changed
            = link_to '取引中'
          %li 
            = link_to '過去の取引'
        .bottom--content__tab
          %ul.bottom--content__tab__item.active
            %li
              = link_to '取引中の商品がありません'
          %ul.bottom--content__tab__item
            %li
              = link_to '過去に取引した商品がありません'

  = render 'item__exhibit'
  = render 'items/footer'