config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", sessions: "users/sessions" }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "items#index"
  resources :items do
    collection do
      get 'exhibit'
      get 'confirm'
      get 'error'
      post 'pay'
      get 'category'
    end
    resources :images, only: [:index, :create]
    resources :goods, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  namespace :api do
      resources :categories, only: :index, defaults: { format: 'json' }
    end
  namespace :api do
    resources :sizetypes, only: :index, defaults: { format: 'json' }
  end
  namespace :api do
    resources :brands, only: :index, defaults: { format: 'json' }
  end

  resources :users, only: [:new, :edit, :show] do
    collection do
      get 'log_out'
      get 'register'  
      get 'sign_in'
    end
  end
  resources :signup, only:[:new, :create] do
    collection do
      get 'outsidemember'
      get 'member'
      get 'phonenumber'
      get 'address'
      get 'paymethod' 
      get 'done' 
    end
  end


  resources :cards do
    collection do
      post 'new'
      post 'create'
    end
  end    

end

app/models/item.rb
class Item < ApplicationRecord

  validates :title, presence:true, 
  length:{ maximum:40 } 
  validates :explanation, presence: true, 
  length:{ maximum:1000 }
  validates :status_id, presence: true, numericality: true
  validates :price,
  numericality:{greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :category_id, presence: true, numericality: true

  # validates :sizetype_id, numericality: true

  

  has_many :comments
  has_many :messages
  has_many :images, dependent: :destroy
  has_many :goods
  has_many :users, through: :goods
  
  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :category, optional: true
  belongs_to :seller, optional: true
  belongs_to :buyer, optional: true
  belongs_to :delivery, optional: true
  belongs_to :sizetype,optional: true

  # def gooted? (good_user_id, good_item_id)
  #   likes.where(user_id: good_user_id, item_id: good_item_id).exists?
  # end


  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :delivery


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.limit(10)
  end
  
  def new
  end

  def create
    @item = Item.new(items_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.build
    render action: '/exhibit'
    end
  end
  
  def show
    @user = Item.where(user_id: @item.user_id).order("RAND()").limit(6)
    @category = Item.where(category_id: @item.category_id).order("RAND()").limit(6)
    @good = Good.new
  end
  
  def edit
    #あとで使います
    # @item = Item.find(params[:id])
  end


  def update
    #ログイン機能実装前なのでコメントアウトしてあります

    # if @item.user_id == current_user.id
      if items_params[:sizetype_id]
        @item.update(items_params)
      else
        @item.update(items_params.merge(sizetype_id: nil))
      end
      redirect_to action: :show
  end
  
  def destroy
    # if @item.user_id == current_user.id
      @item.destroy
      redirect_to root_path
  end


  def exhibit
    @item = Item.new
    @item.build_delivery

    @item.images.build


  end

  def confirm
    #id仮置きです
    @user = User.find(1)
    @item = Item.find(1)
    @cards = Card.find(1)
  end

  def pay
    Payjp.api_key = 'sk_test_be508ed036c9c40e55488d6a'
    Payjp::Charge.create(
      amount: 1000, # 決済する値段
      card: params['payjp-token'],
      currency: 'jpy'
    )
    @item = Item.find(7)
  end

  def pay
    @item = Item.find(7)
    Payjp.api_key = 'sk_test_be508ed036c9c40e55488d6a'
    charge = Payjp::Charge.create(
    :amount => @item.price,
    :card => params['payjp-token'],
    :currency => 'jpy',
    )
  end

  def category
    @categories = Category.where(ancestry: nil)
  end

  private
  def items_params
    params.require(:item).permit(:title, :explanation, :status_id, :price, :category_id, :brand_id, :sizetype_id, delivery_attributes:[:deliveryfee_id, :deliverysource_id, :deliverymethod_id, :deliverydate_id], images_attributes:[:image])
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_comment.html.haml
.detail__comment
  .detail__comment__space
    .detail__comment__space__you
      .detail__comment__space__you--icon
      .detail__comment__space__you--nickname
      .detail__comment__space__you--comment
    .detail__comment__space__i
      .detail__comment__space__i--comment
  .detail__comment--warning
    相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
  %textarea.detail__comment--text
  %input.detail__comment--btn{type: 'submit', value: 'コメントする'}

app/views/items/_footer.html.haml
.footer
  
  .footer__downroad
    .footer__downroad__left
      .footer__downroad__left__top
        スマホでかんたんフリマアプリ
      .footer__downroad__left__middle
        今すぐ無料ダウンロード!
      .footer__downroad__left__bottom
        = link_to image_tag "mercari_icon-f75780e32e41e052c8aaa8b446331cd8.png",class: "merucari-icon"
        = link_to image_tag "app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "store-icon"
        = link_to image_tag "google-play-495575abb895b405aa6336b2a4304958.svg",class: "store-icon"
    .footer__downroad__right
      = image_tag "download_app_pc-a4418175e8be071827ac88d073f40e4a.png",{class: "z"}

  .footer__guide
    .footer__guide__top
      .footer__guide__top__about
        %p.about メルカリについて
        %p.about2 会社概要（運営会社）
        %p.about2 採用情報
        %p.about2 プレスリリース
        %p.about2 公式ブログ
        %p.about2 メルカリロゴ利用ガイドライン
        %i.fab.fa-twitter.fa-2x
        %i.fab.fa-facebook-square.fa-2x
      .footer__guide__top__help
        %p.about ヘルプ＆ガイド
        %p.about2 メルカリガイド
        %p.about2 らくらくメルカリ便
        %p.about2 ゆうゆうメルカリ便
        %p.about2 大型メルカリ便
        %p.about2 車体取引ガイド
        %p.about2 メルカリ安心安全宣言！
        %p.about2 偽ブランド品撲滅の取り組み
      .footer__guide__top__privacy__1
        %p.about プライバシーと利用規約
        %p.about2 プライバシーポリシー
        %p.about2 メルカリ利用規約
        %p.about2 あんしんスマホサポート制度に関する利用特約
        %p.about2 コンプライアンスポリシー
      .footer__guide__top__privacy__2  
        %p.about2 個人データの安全管理に係る基本方針
        %p.about2 特定商取引に関する表記
        %p.about2 資金決済法に基づく表示
        %p.about2 法令順守と犯罪抑止のために
      .footer__guide__top__country
        %p.about 国
        %p.about2 日本
        %p.about2 UnitedStates
    .footer__guide__bottom
      = image_tag "logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg",{class: "q"}
      %div © 2019 Mercari 

app/views/items/_header.html.haml
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

.header
  .header__box
    .header__box__top
      .header__box__top__left
        = link_to "/" do
          = image_tag "logo-acdd90ac4f472d5a6f7a330d33ab1225.svg",class: "merukari"
      .header__box__top__right
        .header__box__top__right__content 
          = form_tag("#",class:"hogeho") do
            = text_field_tag :search ,"",class:"search_form",placeholder: "何かお探しですか？",style: "border-right: none"
            %button{type: "submit",class: "search_button"}
              %i.fas.fa-search
              

    .header__box__bottom
      .header__box__bottom__left
        .header__box__bottom__left__search__category
          = link_to "#" do
            %i.fas.fa-align-justify
          = link_to "カテゴリーから探す",(),class: "category"
          .header__box__bottom__left__search__category__hidden
            %ul.header__box__bottom__left__search__category__hidden__1
              = link_to "" do
                %li.menu
                  1
              = link_to "" do
                %li.menu
                  1
              = link_to "" do
                %li.menu
                  1
              = link_to "" do
                %li.menu
                  1    

            %ul.header__box__bottom__left__search__category__hidden__2
              = link_to "" do
                %li.menu2
                  2
              = link_to "" do
                %li.menu2
                  2
              = link_to "" do
                %li.menu2
                  2
              = link_to "" do
                %li.menu2
                  2    

            %ul.header__box__bottom__left__search__category__hidden__3
              = link_to "" do
                %li.menu3
                  3
              = link_to "" do
                %li.menu3
                  3
              = link_to "" do
                %li.menu3
                  3
              = link_to "" do
                %li.menu3
                  3

        .header__box__bottom__left__search__brand 
          = link_to "#" do
            %i.fas.fa-comment-dollar
            = link_to "ブランドから探す"
            .header__box__bottom__left__search__brand__hidden      
              = link_to "" do
                %li.brand
                  ホビー
              = link_to "" do
                %li.brand
                  ホビー
              = link_to "" do
                %li.brand
                  ホビー
              = link_to "" do
                %li.brand
                  ホビー    

            
    
      - if user_signed_in?
        .header__box__bottom__right
          .header__box__bottom__right__good
            = link_to "#" do
              %i.far.fa-heart
              いいね！一覧

          .header__box__bottom__right__news
            = link_to "#" do
              %i.far.fa-bell
              お知らせ
              .header__box__bottom__right__news__hidden
                = link_to "" do
                  %li.news
                    1
                = link_to "" do
                  %li.news
                    2
                = link_to "" do
                  %li.news
                    3
                = link_to "" do
                  %li.news
                    4   

          .header__box__bottom__right__todo
            = link_to "#" do
              %i.fas.fa-check
              やることリスト
              .header__box__bottom__right__todo__hidden
                .header__box__bottom__right__todo__hidden1

          .header__box__bottom__right__mypage
            = link_to "/users/:id" do
              %i.far.fa-smile
              マイページ
      - else
        .header__box__bottom__right__newuser
          .header__box__bottom__right__good
          =link_to new_user_path, method: :get, class: "newuser_register" do
            新規会員登録
          =link_to new_user_session_path, method: :get, class: "user_login" do
            ログイン

= render "users/item__exhibit"

app/views/items/_items_detail.html.haml
.detail__box
  .detail__box__title
    = @item.title
  .detail__box__items
    .detail__box__items__photo
      .detail__box__items__photo__big
        = image_tag "#{@item.images.first.image}", class: "detail__box__items__photo__big--in"
      .detail__box__items__photo__mini
        - @item.images.each do |item|
          .detail__box__items__photo__mini--1
            = image_tag "#{item.image}" , class: "detail__box__items__photo__mini--1--in"
    %table.detail__box__items__detail
      %tr.detail__box__items__detail__exhibitor
        %th.detail__box__items__detail__exhibitor--right
          出品者
        %td.detail__box__items__detail__exhibitor--left
          %li
            = link_to @item.user.nickname
          %li
            = fa_icon "cog"
            0
            = fa_icon "cog"
            0
            = fa_icon "cog"
            0
      %tr.detail__box__items__detail__category
        %th.detail__box__items__detail__category--right
          カテゴリー
        %td.detail__box__items__detail__category--left
          %li
            = link_to () do
              = @item.category.root.name
          %li
            = link_to () do
              = @item.category.parent.name
          %li
            = link_to () do
              = @item.category.name
          
      %tr.detail__box__items__detail__brand
        %th.detail__box__items__detail__brand--right
          ブランド
        %td.detail__box__items__detail__brand--left
          = @item.brand.name if @item.brand_id.present?
      - if @item.sizetype_id.present?
        %tr.detail__box__items__detail__size
          %th.detail__box__items__detail__size--right
            サイズ
          %td.detail__box__items__detail__size--left 
            = @item.sizetype.sizetype if @item.sizetype_id.present?
      %tr.detail__box__items__detail__status
        %th.detail__box__items__detail__status--right
          商品の状態
        %td.detail__box__items__detail__status--left 
          = @item.status.name
      %tr.detail__box__items__detail__postage
        %th.detail__box__items__detail__postage--right
          配送料の負担 
        %td.detail__box__items__detail__postage--left
          = @item.delivery.deliveryfee.name
      %tr.detail__box__items__detail__method
        %th.detail__box__items__detail__method--right
          配送の方法
        %td.detail__box__items__detail__method--left
          = @item.delivery.deliverymethod.name
      %tr.detail__box__items__detail__area
        %th.detail__box__items__detail__area--right
          配送元の地域
        %td.detail__box__items__detail__area--left
          = link_to @item.delivery.deliverysource.name
      %tr.detail__box__items__detail__date
        %th.detail__box__items__detail__date--right
          配送日の目安
        %td.detail__box__items__detail__date--left
          = @item.delivery.deliverydate.name
  .detail__box__price
    .detail__box__price__box
      %span.detail__box__price__box__price
        ¥
        = @item.price.to_s(:delimited)
      %span.detail__box__price__box__tax
        (税込)
      %span.detail__box__price__box__postage
        - if @item.delivery.deliveryfee_id == 1
          送料込み
        - if @item.delivery.deliveryfee_id == 2
          着払い
  - unless user_signed_in? && item.user_id == current_user.id then
    .detail__box__money
    %input.detail__box__btn{type: 'submit', value: '購入画面に進む'}
  .detail__box__explanation
    = @item.explanation
  - unless user_signed_in? && item.user_id == current_user.id then
    .detail__box__icon
      =  link_to item_goods_path(@item) do
        .detail__box__icon--good
          = fa_icon "heart"
          いいね! 
          = @item.goods.count
      = link_to "" do
        .detail__box__icon--warning
          = fa_icon "flag"
          不適切な商品の報告
      = link_to "" do
        .detail__box__icon--safety
          = fa_icon "lock"
          あんしん・あんぜんへの取り組み

app/views/items/category.html.haml
.categories-wrapper
  .categories-container
    #page-top.categories-button-group
      %h2 カテゴリー一覧
      .categories-button-group__box
        - @categories.each do |category|
          = link_to "##{category.id}" do
            = category.name
    .categories__main
      - @categories.each do |category|
        .categories__list
          .category__name
            %h3{ id: "#{category.id}" }=category.name 
          .category__groups
            .category__all
              %P= link_to "すべて", ''
            - category.children.each do |child|
              .category__child-name
                %h4=child.name
                .category__groups__box
                  .category__ground-children__groups
                    - child.children.each do |ground_child|
                      .category__groundchild-name
                        %p
                          = link_to '' do
                            = ground_child.name
  
  .top-button
    =link_to '#page-top' do
      %i.fa.fa-angle-double-up
      %p Page-Top
          

app/views/items/edit.html.haml
.item-wrapper
  .main_exhibit
    .title
      %h2 商品商品の情報を入力
    = form_with model: @item, local: true do |f|
      .item-image
        .item-image__sub-title
          .item-image__sub-title__caution
            %h3 出品画像
            %span 必須
          %p 最大10枚までアップロードできます
        .item-image__sub-title__area  
          ドラッグアンドドロップまたはクリックしてファイルをアップロード


      .item-title
        .item-title__name
          .item-title__name__caution
            %h3 商品名
            %span 必須
          = f.text_field "title", placeholder: "商品名（必須 40文字まで）", class:'item-title__name__area' 
        .item-title__explanation
          .item-title__explanation__caution
            %h3 商品の説明
            %span 必須
          = f.text_area "explanation", placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', class:'item-title__explanation__area' 
          
      .item-category
        %h3 商品の詳細
        .item-category__choice
          .item-category__choice__main
            .item-category__choice__main-title
              %h3 カテゴリー
              %span 必須
            = f.collection_select :category_id, Category.where(ancestry: nil ), :id, :name, prompt: "---"
            
            %select.category_children
            %select.category_g_children{name:"item[category_id]"}

          .item-category__choice__size
            .item-category__choice__size-title
              %h3 サイズ
              %span 必須
            %select.item-category__choice__size-area{name:"item[sizetype_id]", value:"",type:"hidden"}
          
          .item-category__choice__brand
            .item-category__choice__brand-title
              %h3 ブランド
              %span 任意
            %input{name:"item[brand_id]", value:"",type:"hidden", class:"brand_choice"}
            %input{placeholder: "例) シャネル", value:"",class:'item-category__choice__brand-area'}
              
            %div.brands_area
              %ul.brand_area
              

          .item-category__choice__status
            .item-category__choice__status-title
              %h3 商品の状態
              %span 必須
            = f.collection_select :status_id, Status.all, :id, :name, prompt: "---"

      .item-delivery
        .item-delivery--title
          %h3 配送について
          =link_to '' do
            %i.fa.fa-question-circle
        .item-delivery__choice
          = f.fields_for :delivery do |d|
            .item-delivery__choice__payer
              .item-delivery__choice__payer-title
                %h3 配送料の負担
                %span 必須
              .item-delivery__choice__payer-area
                = d.collection_select :deliveryfee_id, Deliveryfee.all, :id, :name, prompt: "---"

            .item-delivery__choice__region
              .item-delivery__choice__region-title
                %h3 発送元の地域
                %span 必須
              .item-delivery__choice__region-area
                = d.collection_select :deliverysource_id, Prefecture.all, :id, :name, prompt: "---"
            
            .item-delivery__choice__method
              .item-delivery__choice__method-title
                %h3 配送の方法
                %span 必須
              .item-delivery__choice__method-area
                = d.collection_select :deliverymethod_id, Deliverymethod.all, :id, :name, prompt: "---"

            .item-delivery__choice__date
              .item-delivery__choice__date-title
                %h3 発送までの日数
                %span 必須
              .item-delivery__choice__date-area
                = d.collection_select :deliverydate_id, Deliverydate.all, :id, :name, prompt: "---"
      
      .item-price
        .item-price--title
          %h3 販売価格(300〜9,999,999)
          =link_to '' do
            %i.fa.fa-question-circle
            
        .item-price__choice
          .item-price__choice__input
            .item-price__choice__input-title
              %h3 価格
              %span 必須
            .item-price__choice__input-area
              %label ¥
              = f.text_field "price", placeholder: "例） 300"
              
          
          .item-price__choice__fee
            .item-price__choice__fee-title
              %h3 販売手数料 (10%)
            .item-price__choice__fee-area -
          
          .item-price__choice__profit
            .item-price__choice__profit-title
              %h3 販売利益
            .item-price__choice__profit-area -

      .item-post
        .item-post__caution
          %p
          =link_to '禁止されている出品'
          、
          =link_to '行為'
          を必ずご確認ください。
          %br
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          =link_to '偽ブランドの販売'
          は犯罪であり処罰される可能性があります。
          また、出品をもちまして
          =link_to '加盟店規約'
          に同意したことになります。
        = f.submit '変更する', class: 'item-post__exhibit .btn'
        .item-post__return.btn
          = link_to 'キャンセル', '/users/:id'
          -# user_path(current_user)ログイン実装前のため
  

app/views/items/error.html.haml
.errorpage
  エラーが発生しました。

app/views/items/exhibit.html.haml
.item-wrapper
  .main_exhibit
    .title
      %h2 商品商品の情報を入力
    #form
      = form_for (@item) do |f|
        = render 'layouts/error_messages', model: f.object
        .item-img
          .item-img__sub-title
            .item-img__sub-title__caution
              %h3 出品画像
              %span 必須
            %p 最大10枚までアップロードできます
          #image-box-1
            %ul.item-images.active
            .item-num-0#image-box__container
              = f.fields_for :images do |i|
                .input-area
                  = i.label :image, for:nil do
                    =i.file_field :image, name:"item[images_attributes][][image]",type: "file", multiple:true
                    %p ドラッグアンドドロップ またはクリックしてファイルをアップロード
        .item-title
          .item-title__name
            .item-title__name__caution
              %h3 商品名
              %span 必須
            = f.text_field "title", placeholder: "商品名（必須 40文字まで）", class:'item-title__name__area' 
          .item-title__explanation
            .item-title__explanation__caution
              %h3 商品の説明
              %span 必須
            = f.text_area "explanation", placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', class:'item-title__explanation__area' 
            
        .item-category
          %h3 商品の詳細
          .item-category__choice
            .item-category__choice__main
              .item-category__choice__main-title
                %h3 カテゴリー
                %span 必須
              = f.collection_select :category_id, Category.where(ancestry: nil ), :id, :name, prompt: "---"
              %select.category_children
              %select.category_g_children{name:"item[category_id]"}

            .item-category__choice__size
              .item-category__choice__size-title
                %h3 サイズ
                %span 必須
              %select.item-category__choice__size-area
            
            .item-category__choice__brand
              .item-category__choice__brand-title
                %h3 ブランド
                %span 任意
              %input{name:"item[brand_id]", value:"",type:"hidden", class:"brand_choice"}
              %input{placeholder: "例) シャネル", value:"",class:'item-category__choice__brand-area'}
                
              %div.brands_area
                %ul.brand_area
                    
            .item-category__choice__status
              .item-category__choice__status-title
                %h3 商品の状態
                %span 必須
              = f.collection_select :status_id, Status.all, :id, :name, prompt: "---"

        .item-delivery
          .item-delivery--title
            %h3 配送について
            =link_to '' do
              %i.fa.fa-question-circle
          .item-delivery__choice
            = f.fields_for :delivery do |d|
              .item-delivery__choice__payer
                .item-delivery__choice__payer-title
                  %h3 配送料の負担
                  %span 必須
                .item-delivery__choice__payer-area
                  = d.collection_select :deliveryfee_id, Deliveryfee.all, :id, :name, prompt: "---"

              .item-delivery__choice__region
                .item-delivery__choice__region-title
                  %h3 発送元の地域
                  %span 必須
                .item-delivery__choice__region-area
                  = d.collection_select :deliverysource_id, Prefecture.all, :id, :name, prompt: "---"
              
              .item-delivery__choice__method
                .item-delivery__choice__method-title
                  %h3 配送の方法
                  %span 必須
                .item-delivery__choice__method-area
                  = d.collection_select :deliverymethod_id, Deliverymethod.all, :id, :name, prompt: "---"

              .item-delivery__choice__date
                .item-delivery__choice__date-title
                  %h3 発送までの日数
                  %span 必須
                .item-delivery__choice__date-area
                  = d.collection_select :deliverydate_id, Deliverydate.all, :id, :name, prompt: "---"
        
        .item-price
          .item-price--title
            %h3 販売価格(300〜9,999,999)
            =link_to '' do
              %i.fa.fa-question-circle
              
          .item-price__choice
            .item-price__choice__input
              .item-price__choice__input-title
                %h3 価格
                %span 必須
              .item-price__choice__input-area
                %label ¥
                = f.text_field "price", placeholder: "例） 300"
                
            
            .item-price__choice__fee
              .item-price__choice__fee-title
                %h3 販売手数料 (10%)
              .item-price__choice__fee-area -
            
            .item-price__choice__profit
              .item-price__choice__profit-title
                %h3 販売利益
              .item-price__choice__profit-area -

        .item-post
          .item-post__caution
            %p
            =link_to '禁止されている出品'
            、
            =link_to '行為'
            を必ずご確認ください。
            %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            =link_to '偽ブランドの販売'
            は犯罪であり処罰される可能性があります。
            また、出品をもちまして
            =link_to '加盟店規約'
            に同意したことになります。
          = f.submit '出品する', class: 'item-post__exhibit .btn'
          .item-post__return.btn
            =link_to 'もどる', '/users/1'

app/views/items/show.html.haml
.background
  = render 'header'
  .detail
    = render 'items_detail'
    -# - if user_signed_in? && item.user_id == current_user.id
    .edittt
      = link_to edit_item_path do
        .edittt__red-btn
          編集
      .edittt__or
        or
      %input.edittt__stop-btn{type: 'submit', value: '出品を一旦停止する'}
      = link_to item_path(@item), method: :delete, data: { confirm: '確認削除すると二度と復活できません。削除する代わりに停止することもできます。本当に削除しますか？' } do
        .edittt__delete-btn
          この商品を削除する
    = render 'comment'
    .detail__link
      .detail__link--left
        = link_to "＜未使用☆Cartier カルティエ 二つ折り 財布"
      .detail__link--right
        = link_to "マイワリサ mywarisa 35 21.9 バレエシューズ＞"
    .detail__icon
      .detail__icon__box
        .detail__icon__box--facebook
          = fa_icon "facebook-square"
        .detail__icon__box--twitter
          = fa_icon "twitter"
        .detail__icon__box--pinterest
          = fa_icon "pinterest"
    .detail__otheritems
      .detail__otheritems__head
        = link_to "#{@item.user.nickname}さんのその他の出品"
      .detail__otheritems__mass
        - @user.each do |item|
          .detail__otheritems__mass__one
            .detail__otheritems__mass__one--photo
              = image_tag "#{item.images.first.image}", class: "detail__otheritems__mass__one--photo--in"
            .detail__otheritems__mass__one--explanation
              .detail__otheritems__mass__one--explanation--name
                = "#{item.title}"
              .detail__otheritems__mass__one--explanation--price
                ¥
                = "#{item.price}"
    .detail__samecategory
      .detail__samecategory__head
        = link_to "#{@item.category.name} (#{@item.category.parent.name}) その他の商品"
      .detail__samecategory__mass
        - @category.each do |category|
          .detail__samecategory__mass__one
            .detail__samecategory__mass__one--photo
              = image_tag "", class: "detail__samecategory__mass__one--photo--in"
            .detail__samecategory__mass__one--explanation
              .detail__samecategory__mass__one--explanation--name
                = "#{category.title}"
              .detail__samecategory__mass__one--explanation--price
                ¥
                = "#{category.price}"
  = render 'users/item__exhibit'
  = render 'footer'